events 
{
    worker_connections 1024;
}

http
{
    server
    {
        listen 443 ssl;
        # listen 80;
        # listen[::]:443 ssl;   # Supposedely for ipv6
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_certificate /etc/nginx/ssl/inception.crt;       # our SSL/TLS keys
        ssl_certificate_key /etc/nginx/ssl/inception.key;   # we generated in nginx Dockerfile

        server_name ldalmass.42.fr; # https url to use, needs to add a rule in HOST file to redirect to ldalmass.42.fr
        include /etc/nginx/mime.types; # fixes wordpress css not working

        access_log /etc/nginx/access.log;
        error_log /etc/nginx/error.log;

        # Target all index pages in ldalmass.42.fr/[index]
        location /
        {
            # root  /var/www/html/;
            index  index.html index.php index.htm;
            try_files $uri $uri/ =404;  # each unknown request are redirected to 404 error
        }

        # Target every php requests
        location ~ \.php$
        {
            root  /var/www/wordpress/;
            fastcgi_index index.php;
            fastcgi_pass wordpress:9000;    # redirect request to port 9000 because php is used there (installed in wordpress docker)
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
    }
}
