services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
    - "443:443"
    - "80:80"
    networks:
      - inception
    restart: always
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: user_password
    networks:
      - inception
    restart: always
  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    networks:
      - inception
    depends_on:
      - nginx
    restart: always

networks:
  inception:
    driver: bridge

# volumes:
#   - ./mysql_data:/var/lib/mysql
